Add ATX Header Support for `terraform-docs`
cisagov/skeleton-generic pull request #164
Opened 2024-01-22 18:47 UTC by michaelsaki

#  #

## 🗣 Description ##

This pull request:

- Clones @mcdonnnj's forked branch from `terraform-docs`.
- Builds and installs the binary from the clone.

## 💭 Motivation and context ##

This temporarily resolves [#196](https://github.com/cisagov/skeleton-tf-module/issues/196) until @mcdonnnj's changes get merged into `terraform-docs`, at which point we can change back over to the standard of installing `terraform-docs`.

## 🧪 Testing ##

All automated tests passed. I also used [act](https://github.com/nektos/act) for local testing to make sure the workflow would behave like it should.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-01-22 19:37 UTC, mcdonnnj requested changes
Thanks for working on this! Some feedback for your consideration.

2024-01-22 19:37 UTC, mcdonnnj commented on .github/workflows/build.yml
>    RUN_TMATE: ${{ secrets.RUN_TMATE }}
I'd prefer these prepended to make it clear how they're being used.

```suggestion
  CURL_CACHE_DIR: ~/.cache/curl
  PIP_CACHE_DIR: ~/.cache/pip
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit
  RUN_TMATE: ${{ secrets.RUN_TMATE }}
  TERRAFORM_DOCS_BRANCH_NAME: improvement/support_atx_closed_markdown_headers
  TERRAFORM_DOCS_REPO_DEPTH: 1
  TERRAFORM_DOCS_REPO_URL: https://github.com/mcdonnnj/terraform-docs.git
```

2024-01-22 19:37 UTC, mcdonnnj commented on .github/workflows/build.yml
> +           --depth=$DEPTH $REPO_URL /tmp/terraform-docs
In line with the previous suggestion.

```suggestion
          git clone --single-branch \
           --branch $TERRAFORM_DOCS_BRANCH_NAME \
           --depth=$TERRAFORM_DOCS_REPO_DEPTH \
           $TERRAFORM_DOCS_REPO_URL /tmp/terraform-docs
```

2024-01-22 19:37 UTC, mcdonnnj commented on .github/workflows/build.yml
> +          echo "$GOBIN" >> $GITHUB_PATH
I believe the PATH is handled by [actions/setup-go](https://github.com/actions/setup-go/blob/0c52d547c9bc32b1aa3301fd7a9cb496313a4491/src/main.ts#L44). We can also take advantage of the `-C` switch to handle building from the cloned repository.

```suggestion
          go build \
          -C /tmp/terraform-docs \
          -o $(go env GOPATH)/bin/terraform-docs
```

2024-01-22 19:47 UTC, jsf9k requested changes
Some very minor things...

2024-01-22 19:47 UTC, jsf9k commented on .github/workflows/build.yml
> +      # terraform-docs is ran during lint.
Grammar:
```suggestion
      # terraform-docs is run during linting.
```

2024-01-22 19:47 UTC, jsf9k commented on .github/workflows/build.yml
> +      # is approved. This temporary fix will allow for ATX Header Support when
Remove unnecessary caps:
```suggestion
      # is approved. This temporary fix will allow for ATX header support when
```

2024-01-22 19:47 UTC, jsf9k commented on .github/workflows/build.yml
> +      - name: Clone ATX Headers branch from Terraform-docs Fork
Remove needless capitalization:
```suggestion
      - name: Clone ATX headers branch from terraform-docs fork
```

2024-01-22 19:47 UTC, jsf9k commented on .github/workflows/build.yml
> +      - name: Build and Install Terraform-docs Binary
Remove needless capitals:
```suggestion
      - name: Build and install terraform-docs binary
```

2024-01-22 20:32 UTC, dav3r commented on .github/workflows/build.yml
> +      # terraform-docs is run during linting.
Please create an issue in this repo about changing from @mcdonnnj's fork back to the main `terraform-docs` repo after https://github.com/terraform-docs/terraform-docs/pull/745 is (hopefully) merged.  Once the issue has been created, please update the code comment here to be a `TODO` and include a link to that issue.  See [here](https://github.com/cisagov/cool-assessment-provisioner-iam/blob/3235e1f2db56423c52bb13f8460436ffb9d74de4/locals.tf#L46-L50) for an example.

2024-01-22 20:35 UTC, dav3r commented on .github/workflows/build.yml
> +           $TERRAFORM_DOCS_REPO_URL /tmp/terraform-docs
I'm nitpicking here, but in our spirit of alphabetizing, might as well go all in and keep the switches in order:
```suggestion
          git clone \
           --branch $TERRAFORM_DOCS_REPO_BRANCH_NAME \
           --depth $TERRAFORM_DOCS_REPO_DEPTH \
           --single-branch \
           $TERRAFORM_DOCS_REPO_URL /tmp/terraform-docs
```

2024-01-22 20:43 UTC, jsf9k approved these changes

2024-01-23 14:30 UTC, michaelsaki commented on .github/workflows/build.yml
> +      # terraform-docs is run during linting.
@dav3r Please see the changes here: https://github.com/cisagov/skeleton-generic/pull/164/commits/d114fb4233f22cb9edb3e1a6555ca0a677bcfc7e and also the issue created here: [165](https://github.com/cisagov/skeleton-generic/issues/165)

2024-01-23 14:42 UTC, dav3r commented on .github/workflows/build.yml
> +      # terraform-docs is run during linting.
The comment and issue both look great, thanks!  FYI, I made a couple of small formatting edits to #165.

2024-01-23 14:44 UTC, dav3r approved these changes
Thanks for taking care of this! 👍 

Can you please confirm that you re-tested this workflow after making the changes requested during the PR review?

2024-01-23 14:49 UTC, michaelsaki commented
> Thanks for taking care of this! 👍
> 
> Can you please confirm that you re-tested this workflow after making the changes requested during the PR review?

You are welcome! Yes, I ran any changes to the workflow in [act](https://github.com/nektos/act) everything checked out locally.

2024-03-06 01:17 UTC, mcdonnnj approved these changes
:shipit:

2024-03-06 01:25 UTC, merged