Enable terraform validate pre-commit hook
cisagov/skeleton-generic pull request #90
Opened 2021-08-26 14:44 UTC by dav3r

#  #

## 🗣 Description ##

This PR enables the `terraform validate` pre-commit hook.

## 💭 Motivation and context ##

That pre-commit hook had been disabled in all of our repositories because of issues related to proxy providers and Terraform code that uses remote state.  We believe that those issues (see https://github.com/hashicorp/terraform/pull/24887 and https://github.com/hashicorp/terraform/pull/24896) have been corrected in Terraform 0.13.x, which we are in the process of migrating to, so this hook should now work as expected in most, if not all of our repos.

This PR will remain `blocked` until the following conditions have been met:
* [x] All of our repositories that use Terraform have been successfully updated to use Terraform 0.13.x.
* [x] All of our deployed Terraform states have been updated to Terraform 0.13.x.  **It is important to note that we cannot update any Terraform states to 0.14.x until they successfully apply with 0.13.x first.**
* [x] https://github.com/cisagov/setup-env-github-action/pull/37 has been approved and merged.

This PR is a part of cisagov/cool-system#94.  

Similar PRs are:
* cisagov/skeleton-tf-module#57
* cisagov/skeleton-packer#82
* cisagov/skeleton-ansible-role-with-test-user#24

## 🧪 Testing ##

I verified that running `terraform validate` with Terraform 0.13.7 works without any errors in this repository.  I also confirmed that all pre-commit hooks (including the newly-enabled `terraform validate` hook) run successfully.

After I confirmed that pre-commit with Terraform 0.13.7 ran successfully in GitHub Actions via https://github.com/cisagov/skeleton-generic/pull/90/commits/6a7fbf07bd371d0493c523ce24647e5c04c77c03, I reverted that commit (see https://github.com/cisagov/skeleton-generic/pull/90/commits/b51dbb577e02baff361a6494e22f61aa517e28d4) in preparation for when this PR becomes unblocked at the end of downstream testing.

Further testing will be done in all downstream repositories.

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

2021-08-26 19:51 UTC, jsf9k approved these changes
I look forward to the day when `terraform validate` is again looking out for us.

2021-08-27 16:49 UTC, mcdonnnj requested changes
This makes sense. I think we should remove
https://github.com/cisagov/skeleton-generic/blob/6a7fbf07bd371d0493c523ce24647e5c04c77c03/.github/workflows/build.yml#L87-L93
from the workflow because this is handled by the `terraform_validate` hook per [these lines](https://github.com/antonbabenko/pre-commit-terraform/blob/c7d6d002ed510c1a3e63af6d0e132e8abf2448d4/terraform_validate.sh#L84-L117).

2021-08-27 17:02 UTC, dav3r commented
> This makes sense. I think we should remove
> https://github.com/cisagov/skeleton-generic/blob/6a7fbf07bd371d0493c523ce24647e5c04c77c03/.github/workflows/build.yml#L87-L93
> 
> 
> from the workflow because this is handled by the `terraform_validate` hook per [these lines](https://github.com/antonbabenko/pre-commit-terraform/blob/c7d6d002ed510c1a3e63af6d0e132e8abf2448d4/terraform_validate.sh#L84-L117).

Good call- I had forgotten about that!  See https://github.com/cisagov/skeleton-generic/pull/90/commits/895a692ad8dfc3df50b1c2c9a79bca7166b5f5f2.

2021-09-11 14:21 UTC, dav3r commented
@mcdonnnj - please review this when you can.

2021-09-13 13:51 UTC, mcdonnnj approved these changes
Since it doesn't seem to barf in [this branch](https://github.com/cisagov/skeleton-generic/tree/testing/dependabot_for_terraform), do we want to add

```yaml
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
```

to `.github/dependabot.yml` since we are hitting the minimum version of Terraform needed to support Dependabot alerts? This would resolve https://github.com/cisagov/skeleton-tf-module/issues/59 downstream and also cover (with modification of the `directory` when doing PRs) the same need in [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer) and [cisagov/skeleton-ansible-role-with-test-user](https://github.com/cisagov/skeleton-ansible-role-with-test-user).

2021-09-13 13:54 UTC, dav3r commented
> Since it doesn't seem to barf in [this branch](https://github.com/cisagov/skeleton-generic/tree/testing/dependabot_for_terraform), do we want to add
> 
> ```yaml
>   - package-ecosystem: "terraform"
>     directory: "/"
>     schedule:
>       interval: "weekly"
> ```
> 
> to `.github/dependabot.yml` since we are hitting the minimum version of Terraform needed to support Dependabot alerts? This would resolve [cisagov/skeleton-tf-module#59](https://github.com/cisagov/skeleton-tf-module/issues/59) downstream and also cover (with modification of the `directory` when doing PRs) the same need in [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer) and [cisagov/skeleton-ansible-role-with-test-user](https://github.com/cisagov/skeleton-ansible-role-with-test-user).

My gut says to push that dependabot change to an upcoming Kraken and separate it from this TF 0.13 business.  What do you think?

2021-09-13 13:56 UTC, mcdonnnj commented
> 
> 
> > Since it doesn't seem to barf in [this branch](https://github.com/cisagov/skeleton-generic/tree/testing/dependabot_for_terraform), do we want to add
> > ```yaml
> >   - package-ecosystem: "terraform"
> >     directory: "/"
> >     schedule:
> >       interval: "weekly"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to `.github/dependabot.yml` since we are hitting the minimum version of Terraform needed to support Dependabot alerts? This would resolve [cisagov/skeleton-tf-module#59](https://github.com/cisagov/skeleton-tf-module/issues/59) downstream and also cover (with modification of the `directory` when doing PRs) the same need in [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer) and [cisagov/skeleton-ansible-role-with-test-user](https://github.com/cisagov/skeleton-ansible-role-with-test-user).
> 
> My gut says to push that dependabot change to an upcoming Kraken and separate it from this TF 0.13 business. What do you think?

I'm ok with that. I only mentioned it because I would also be willing to consider it part of Terraform 0.13 jazz.

2021-09-13 14:09 UTC, dav3r commented
> > My gut says to push that dependabot change to an upcoming Kraken and separate it from this TF 0.13 business. What do you think?
> 
> I'm ok with that. I only mentioned it because I would also be willing to consider it part of Terraform 0.13 jazz.

👍   Please reference this PR when you create a new PR with that dependabot change and we will decide when it makes the most sense to roll that one out.

2021-09-13 14:39 UTC, merged